// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUebZ9PFos-w9Z9tIlQFp3Vk6SWmRw4Z4',
    appId: '1:907121313533:web:747cbed3a7d25c483f6094',
    messagingSenderId: '907121313533',
    projectId: 'cliko-web',
    authDomain: 'cliko-web.firebaseapp.com',
    storageBucket: 'cliko-web.appspot.com',
    measurementId: 'G-06MT0M12MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp27hBB1XgRa9yvH-OB3tqWLukIyscSrE',
    appId: '1:907121313533:android:75740849d6fce4453f6094',
    messagingSenderId: '907121313533',
    projectId: 'cliko-web',
    storageBucket: 'cliko-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT7yejlP1BZa16u6KtLzZzZ5VWUokXflo',
    appId: '1:907121313533:ios:4cbf4f62b786615e3f6094',
    messagingSenderId: '907121313533',
    projectId: 'cliko-web',
    storageBucket: 'cliko-web.appspot.com',
    iosClientId: '907121313533-tn7m3jekbcmglengb93ghgnqkd3eonhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.clikoWeb',
  );
}
